export default {
  title: '🃏 牌库制作',
  actions: {
    newDeck: '新建牌库',
    refresh: '刷新',
    save: '保存',
    delete: '删除牌库',
    cancel: '取消',
    create: '创建',
    confirm: '确认',
    back: '返回编辑',
    next: '下一步',
    prev: '上一步',
    exportTTS: '导出为TTS物品',
    saveDeck: '保存牌库',
    openDirectory: '打开导出目录',
    uploadToGithub: '一键上传到GitHub',
    generateTTS: '生成TTS文件',
    copyUrl: '复制URL',
    openSteamWorkshop: '打开Steam Workshop'
  },
  panels: {
    myDecks: '我的牌库',
    deckEditor: '牌库编辑器'
  },
  forms: {
    newDeck: {
      title: '新建牌库',
      name: '牌库名称',
      namePlaceholder: '请输入牌库名称',
      width: '宽度 (1-10)',
      height: '高度 (1-7)',
      widthPlaceholder: '宽度',
      heightPlaceholder: '高度'
    },
    validation: {
      nameRequired: '请输入牌库名称',
      nameLength: '牌库名称长度在1-50个字符',
      namePattern: '牌库名称不能包含特殊字符 \\/:*?"<>|',
      widthRequired: '请输入宽度',
      widthRange: '宽度必须在1-10之间',
      heightRequired: '请输入高度',
      heightRange: '高度必须在1-7之间'
    }
  },
  deckList: {
    grid: '网格',
    empty: '暂无牌库',
    emptyDesc: '点击上方按钮创建新牌库'
  },
  deleteDialog: {
    title: '删除确认',
    warning: '警告',
    message: '此操作不可恢复，确定要删除牌库"{name}"吗？'
  },
  noSelection: {
    title: '请选择一个牌库开始编辑',
    description: '从左侧列表选择一个牌库，或创建新的牌库'
  },
  // 牌库编辑器部分
  editor: {
    shortcuts: {
      save: '(Ctrl+S)'
    },
    sides: {
      front: '正面',
      back: '背面',
      frontWithIcon: '🎯 正面',
      backWithIcon: '🎲 背面'
    },
    content: {
      selectContent: '选择内容',
      selectContentFor: '选择内容 - {side}',
      clickToAdd: '点击添加内容',
      sideIndicator: {
        front: '正面',
        back: '背面'
      }
    },
    tabs: {
      cards: '🎯 卡牌',
      cardbacks: '🎴 卡背',
      images: '🖼️ 图片'
    },
    search: {
      cards: '搜索卡牌名称...',
      images: '搜索图片文件...'
    },
    cardbacks: {
      player: '玩家卡背',
      encounter: '遭遇卡背'
    },
    empty: {
      noCards: '没有找到匹配的卡牌',
      noImages: '没有找到匹配的图片'
    }
  },
  // TTS导出引导部分
  ttsExport: {
    title: 'TTS导出引导',
    steps: {
      step1: {
        number: '1',
        title: '导出图片',
        description: '将您的牌库正面和背面导出为图片文件，这些图片将用于在TTS中显示您的卡牌。',
        header: '📷 第一步：导出牌库图片'
      },
      step2: {
        number: '2',
        title: '上传图床',
        description: '将导出的图片上传到图床，获取在线地址供TTS使用。',
        header: '☁️ 第二步：上传到图床'
      },
      step3: {
        number: '3',
        title: '生成TTS文件',
        description: '使用上传的图片URL生成桌游模拟器可导入的牌组文件。',
        header: '🎯 第三步：生成TTS文件'
      }
    },
    export: {
      title: '导出设置',
      format: '导出格式',
      formatPlaceholder: '选择图片格式',
      quality: '图片质量',
      qualityMarks: {
        60: '低',
        70: '中',
        80: '高',
        90: '极高',
        100: '最高'
      },
      startExport: '开始导出图片',
      exporting: '正在导出...',
      openDirectory: '打开导出目录',
      exportedFiles: '导出的文件：'
    },
    imageHost: {
      title: '选择图床服务',
      steam: {
        name: 'Steam 云存储',
        description: '推荐：使用Steam Workshop云存储，稳定可靠',
        instruction: '请先将图片上传到Steam Workshop，然后将获取到的图片URL地址填写到下方。'
      },
      github: {
        name: 'GitHub图床',
        description: '便捷：一键上传到GitHub仓库图床服务',
        notConfigured: '请先在设置页面配置GitHub Token和仓库信息。',
        configured: '已连接到GitHub，用户：{username}',
        checking: '正在检查GitHub配置...',
        verifying: '正在验证GitHub登录状态...'
      },
      urls: {
        frontImage: '正面图片URL',
        backImage: '背面图片URL',
        frontPlaceholder: '请输入正面图片的Steam云存储URL',
        backPlaceholder: '请输入背面图片的Steam云存储URL',
        autoGenerated: '上传后自动生成'
      }
    },
    upload: {
      frontImage: '正面图片',
      backImage: '背面图片',
      uploading: '正在上传...',
      waiting: '等待中',
      success: '成功',
      error: '错误',
      uploadingTitle: '正在上传...',
      uploadSuccess: '成功上传 {count} 张图片',
      urlsGenerated: 'URL已自动填入上方输入框，可点击复制按钮进行复制。'
    },
    generate: {
      title: 'TTS文件配置',
      deckName: '牌库名称',
      cardCount: '卡牌总数',
      frontImageUrl: '正面图片URL',
      backImageUrl: '背面图片URL',
      description: 'TTS文件将会生成到以下位置：',
      location: '我的文档/My Games/Tabletop Simulator/Saves/Saved Objects/阿卡姬制作/',
      includes: '文件包含：',
      includesList: {
        config: 'TTS JSON配置文件（包含完整的牌组数据和脚本）',
        thumbnail: '256x256像素的PNG封面图片'
      },
      generating: '正在生成TTS文件...',
      complete: '完成并返回编辑',
      retry: '重新生成',
      backToStep: '返回上一步'
    },
    navigation: {
      nextExport: '下一步：导出图片',
      nextUpload: '下一步：上传到图床',
      nextGenerate: '下一步：生成TTS文件'
    }
  },
  messages: {
    refreshSuccess: '牌库列表已刷新',
    loadFailed: '加载牌库列表失败，请重试',
    createSuccess: '牌库创建成功',
    createFailed: '创建牌库失败，请重试',
    saveSuccess: '牌库保存成功',
    saveFailed: '保存牌库失败，请重试',
    deleteSuccess: '牌库删除成功',
    deleteFailed: '删除牌库失败，请重试',
    loadCardsFailed: '加载可用卡牌失败',
    loadImagesFailed: '加载可用图片失败',
    // 编辑器相关消息
    cardAdded: '{type}已添加到{side}',
    contentRemoved: '内容已移除',
    positionSwapped: '内容位置已调换',
    // TTS导出相关消息
    exportSuccess: '图片导出成功！',
    exportFailed: '图片导出失败: {error}',
    directoryOpened: '已打开导出目录',
    directoryOpenFailed: '打开目录失败: {error}',
    uploadSuccess: 'GitHub图床上传成功！',
    uploadFailed: 'GitHub图床上传失败: {error}',
    generateSuccess: 'TTS文件生成成功！',
    generateFailed: 'TTS文件生成失败: {error}',
    urlCopied: '{label}已复制到剪贴板',
    urlEmpty: '{label}为空，无法复制',
    copyFailed: '复制失败，请手动复制',
    // 类型名称
    types: {
      card: '卡牌',
      cardback: '卡背',
      image: '图片'
    },
    // TTS导出结果消息
    tts: {
      exportSuccess: {
        title: '导出成功！',
        message: '牌库图片已成功导出到DeckBuilder目录。'
      },
      exportFailed: {
        title: '导出失败',
        message: '导出过程中发生错误，请重试。'
      },
      uploadSuccess: {
        title: '上传成功！',
        message: '图片已成功上传到GitHub图床，URL已自动填入。'
      },
      uploadFailed: {
        title: '上传失败',
        message: '上传过程中发生错误，请重试。'
      },
      generateSuccess: {
        title: '🎉 TTS文件生成成功！',
        message: '牌库 "{name}" 已成功导出为TTS文件！文件已保存到TTS游戏目录，您现在可以在桌游模拟器中导入这个牌组了！'
      },
      generateFailed: {
        title: '生成失败',
        message: '生成TTS文件时发生错误，请检查配置后重试。'
      }
    }
  }
}
